### PR TITLE
sectionable_image has position missing

### PR DESCRIPTION
**Pull request by treenewbee**
position field is missing in the sectionable image migration. 

also I ignored the komoproject file.

### CODE REVIEW

**Comment by sindrenm** [comment]
Is it a good idea to just change the migration, or should we create a new migration that adds this field? By changing the migration, those who gave already run this won't actually get the update.

**Comment by treenewbee** [comment]
actually a lot of other stuff are missing/broken when I use it with the latest version of active admin, maybe I will fix them all and use a new migration file.

**Comment by jgorset** [comment]
Hey thanks @treenewbee! :+1: on making a new migration to add the field; that's what migrations are for, after all!

**Comment by jgorset** [comment]
Oh, and what other stuff is broken with the latest version of ActiveAdmin? We'll want to fix that.

**Comment by timkurvers** [comment]
Thanks for chiming in @treenewbee!

Could you remove `.komoproject` from `.gitignore`? It should go into your global ignore file instead:

> Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by `core.excludesFile` in the user’s `~/.gitconfig`

**Comment by treenewbee** [comment]
using active admin version 1.0.0:

two translations are missing
translation missing: en.activerecord.models.knowledge_base
translation missing: en.activerecord.models.knowledge_base/section/kind.other

```
Showing /.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-7e72b7881eb6/app/views/active_admin/resource/new.html.arb where line #2 raised:
undefined method `style' for #<KnowledgeBase::Sectionables::Links::Link:0x007f2936bc25a8>

Showing /.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-e72b7881eb6/app/views/active_admin/resource/index.html.arb where line #2 raised:
`default_actions` is no longer provided in ActiveAdmin 1.x. Use `actions` instead.
```

I guess the active admin generator needs to be updated, assuming it is planning to support 1.x.

**Comment by sindrenm** [comment]
Thanks for the PR and information, @treenewbee. As far as I know, ActiveAdmin 1.0.0 is still in prerelease, and I have a feeling it might take some time before they come out with the real deal. However, since we're providing admin template generators with the gem, we should stay up to speed, so it's great that you mention this. :smiley: 

Also, that “style for Links::Link” issue isn't really related to ActiveAdmin, it's just an oversight on our end. We're simply just trying to create a form field for an attribute that doesn't exist. :smiley: 

`default_actions` has been renamed to just `actions`, so that should be a small change in our templates, and the translations should be an easy fix as well.

You're awesome for bringing this to our attention!

**Pull request closed without merging**
