### PR TITLE
Models should be concerns #1

### PR DESCRIPTION
**Pull request by clyfe**
Models should be concerns #1

### CODE REVIEW

**Comment by clyfe** [comment]
Note there was a test failing in articles controller spec. I didn't touch it.

**Comment by sindrenm** [comment]
Hahaha! Well shit, I just made another branch to fix this as well. Should've looked to see if there was already another PR on it. From what I can see, we've done the exact same thing, although you've also normalized the code a little so that it is more consistent (kudos!). This looks very good indeed. The only thing I'm kinda hesitant about here is _ lib/knowledge_base/concerns/models.rb_. Instead of making new files for those new wrapper concerns, you've made them inline into that file, which kinda breaks the pattern we already had going. Then again, one could argue that putting so little code into separate files looks a little bit overkill.

**Comment by clyfe** [comment]
In regards to models.rb I'm not sure either. It does break the pattern.

**Comment by jgorset** [comment]
Hi @clyfe! I think that's a neat pattern, too, but since it does break I'd be inclined to follow it anyway. Either way, that's a minor detail. Nice pull request! Thanks!

**Comment by clyfe** [comment]
fyi, it's not uncommon. Here's the same thing in rails, with the autoload flavor:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record.rb

**Comment by jgorset** [comment]
That's really interesting, actually. I think it makes a lot of sense to write it that way if you don't have a lot of modules. I'd say in our case it's a wash and you could go either way, but that seems pretty messy in ActiveRecord there. I mean, that's a big-ass file. What do you think?

**Comment by clyfe** [comment]
Yeah, AR is known to be kinda bloated.

**Comment by jgorset** [comment]
I'm gonna merge this anyway! Thanks, @clyfe!

**Pull request merged**
